<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class T_IRAI extends Model
{
    protected $table = 'T_IRAI';
    protected $fillable = ['IRAI_ID','HANSU','TENPO_NAME','CYUMONSYA_NAME','CYUMONSYA_KNAME','SETSAKI_NAME','SETSAKI_KNAME','SETSAKI_POSTNO','SETSAKI_ADDRESS','SETSAKI_TELNO','KOJIGYOSYA_CD','KOJIGYOSYA_NAME','KOJIGYOSYA_NAME','KIBO_YMD1','KIBO_YMD2','KIBO_YMD3','KISETSU_TEL','KISETSU_TEL','KIJIRAN','KIJIRAN_PATH','MOKUTEKI','JYOKYO_CD','ANSWER_CD','COMMENT1','COMMENT2','GYOSYA_ANS_YMD','REF_FLG','VISIVLE_FLG','DEL_FLG','ADD_TANTCD','ADD_YMD','UPD_TANTCD','UPD_YMD'];
    public $timestamps = false;
}
